apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-repository-source
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/fluxcd/whoami-repository`)
      kind: Rule
      services:
        - name: whoami-repository-source
          port: http
  tls: {}