apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- traefik-application.yaml
- whoami-application.yaml
#- whoami-repository-application.yaml
#- whoami-values-application.yaml

